debug: false
server:
  port: 8770
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}(${eureka.instance.ip-address}:${server.port}):v${info.version}:${spring.profiles.active}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Ribbon Config
# ===============================
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 5000
  eager-load:
    enabled: true
    clients: server-oauth2
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  redis:
    url: redis://127.0.0.1:6379
  cloud:
    # ===============================
    # = GateWay Config
    # ===============================
    gateway:
      routes:
        - id: server-oauth2
          uri: lb://server-oauth2
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: GateWayHystrix
                fallbackUri: forward:/hystrixhandle
        - id: server-oauth2-open
          uri: lb://server-oauth2
          predicates:
            - Path=/open/oauth/**
          filters:
            - RewritePath=/open/oauth/(?<segment1>.*),/open/$\{segment}
            - name: Hystrix
              args:
                name: GateWayHystrix
                fallbackUri: forward:/hystrixhandle