spring:
  profiles:
    active: dev
  application:
    name: server-oauth2
info:
  app:
    name: ${spring.application.name}
    version: 1.1.0
  build:
    author: zhangbin
    active: ${spring.profiles.active}