spring:
  profiles:
    active: dev
  application:
    name: server-log
info:
  version: 1.1.0
  app-name: ${spring.application.name}
  tags:
    environment: ${spring.profiles.active}
  build:
    author: zhangbin
    active: ${spring.profiles.active}