debug: false
server:
  address: 127.0.0.1
  port: 8780
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/log-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file:
    max-size: 5MB
    max-history: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Spring Config
# ===============================
spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        log_output:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: app-log
          content-type: application/json
        # 与@StreamListener注解中的value一致，是绑定的渠道名
        log_input:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: app-log
          group: app-log-group
          content-type: application/json
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}(${eureka.instance.ip-address}:${server.port}):v${info.version}:${spring.profiles.active}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: dbd1458a-19fb-11e9-894e-d8c49792dd7b
      client-secret: E0D3024D-9A22-41EE-AC0F-FC6B56E367AE
    resource:
      token-info-uri: http://server-oauth2/oauth/check_token
acp:
  swagger:
    enabled: true
  schedule:
    crons:
      LogFileBackUpTask: 0 0/1 * * * ?